# Generated by Django 5.2.1 on 2025-05-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_aluno_curso_alter_aluno_escolaridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
