# Generated by Django 5.1.7 on 2025-04-08 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('preco_produto', models.FloatField()),
                ('desc_produto', models.CharField(max_length=200)),
                ('categoria_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.categoria')),
            ],
        ),
    ]
