# Generated by Django 5.1.7 on 2025-04-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alternativa',
            new_name='Produto',
        ),
    ]
